"""initial schema

Revision ID: fdc9a82eee1a
Revises: 
Create Date: 2026-07-16 12:44

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdc9a82eee1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_contact_name'), 'listing_contact', ['name'], unique=False)
    op.create_table('home_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatherId', sa.Integer(), nullable=True),
    sa.Column('externalId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interiorEntityKey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fatherInteriorEntityKey', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('category', sa.Enum('ONE_STORY_HOUSE', 'RESIDENTIAL_BUILDING', 'MULTI_STORY_HOUSE', name='home_doc_category_enum'), nullable=False),
    sa.Column('type', sa.Enum('PROPERTY', 'FLOOR', 'APARTMENT', 'ROOM', 'ROOM_FURNITURE', 'ROOM_STUFF', 'ROOM_INSTRUMENT', name='home_doc_type_enum'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extraData', sa.JSON(), nullable=True),
    sa.Column('listingAgentId', sa.Integer(), nullable=True),
    sa.Column('listingOfficeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fatherId'], ['home_docs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listingAgentId'], ['listing_contact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listingOfficeId'], ['listing_contact.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_docs_externalId'), 'home_docs', ['externalId'], unique=False)
    op.create_index(op.f('ix_home_docs_fatherId'), 'home_docs', ['fatherId'], unique=False)
    op.create_index(op.f('ix_home_docs_interiorEntityKey'), 'home_docs', ['interiorEntityKey'], unique=True)
    op.create_index(op.f('ix_home_docs_listingAgentId'), 'home_docs', ['listingAgentId'], unique=False)
    op.create_index(op.f('ix_home_docs_listingOfficeId'), 'home_docs', ['listingOfficeId'], unique=False)
    op.create_table('chattels_specs_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homeDocId', sa.Integer(), nullable=False),
    sa.Column('colors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['homeDocId'], ['home_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chattels_specs_attributes_homeDocId'), 'chattels_specs_attributes', ['homeDocId'], unique=False)
    op.create_table('home_docs_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homeDocId', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['homeDocId'], ['home_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homeDocId')
    )
    op.create_table('home_docs_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homeDocId', sa.Integer(), nullable=False),
    sa.Column('subHomeDocId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homeDocId'], ['home_docs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subHomeDocId'], ['home_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homeDocId', 'subHomeDocId', name='uq_home_docs_relations_pair')
    )
    op.create_index(op.f('ix_home_docs_relations_homeDocId'), 'home_docs_relations', ['homeDocId'], unique=False)
    op.create_index(op.f('ix_home_docs_relations_subHomeDocId'), 'home_docs_relations', ['subHomeDocId'], unique=False)
    op.create_table('listing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('listingType', sa.Enum('Standard', 'New Construction', 'Foreclosure', 'Short Sale', name='listing_type_enum'), nullable=True),
    sa.Column('listedDate', sa.DateTime(), nullable=True),
    sa.Column('removedDate', sa.DateTime(), nullable=True),
    sa.Column('daysOnMarket', sa.Integer(), nullable=True),
    sa.Column('residenceId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['residenceId'], ['home_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_history_residenceId'), 'listing_history', ['residenceId'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residenceId', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('hoaFee', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Float(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('listingStatus', sa.Enum('active', 'inactive', name='listing_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['residenceId'], ['home_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_residenceId'), 'listings', ['residenceId'], unique=False)
    op.create_table('residence_specs_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homeDocId', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('subEntitiesQuantity', sa.Integer(), nullable=True),
    sa.Column('constructionYear', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeDocId'], ['home_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residence_specs_attributes_homeDocId'), 'residence_specs_attributes', ['homeDocId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_residence_specs_attributes_homeDocId'), table_name='residence_specs_attributes')
    op.drop_table('residence_specs_attributes')
    op.drop_index(op.f('ix_listings_residenceId'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_listing_history_residenceId'), table_name='listing_history')
    op.drop_table('listing_history')
    op.drop_index(op.f('ix_home_docs_relations_subHomeDocId'), table_name='home_docs_relations')
    op.drop_index(op.f('ix_home_docs_relations_homeDocId'), table_name='home_docs_relations')
    op.drop_table('home_docs_relations')
    op.drop_table('home_docs_dimensions')
    op.drop_index(op.f('ix_chattels_specs_attributes_homeDocId'), table_name='chattels_specs_attributes')
    op.drop_table('chattels_specs_attributes')
    op.drop_index(op.f('ix_home_docs_listingOfficeId'), table_name='home_docs')
    op.drop_index(op.f('ix_home_docs_listingAgentId'), table_name='home_docs')
    op.drop_index(op.f('ix_home_docs_interiorEntityKey'), table_name='home_docs')
    op.drop_index(op.f('ix_home_docs_fatherId'), table_name='home_docs')
    op.drop_index(op.f('ix_home_docs_externalId'), table_name='home_docs')
    op.drop_table('home_docs')
    op.drop_index(op.f('ix_listing_contact_name'), table_name='listing_contact')
    op.drop_table('listing_contact')
    # ### end Alembic commands ###
